name: Python Applications

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov python-dotenv  # Include all necessary packages
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Debug
      run: |
        echo "Python version:"
        python --version
        echo "PYTHONPATH:"
        echo $PYTHONPATH

    - name: Test with pytest for Application 1
      run: |
        echo "Running tests for the main application..."
        pytest --pylint --cov  # Adjust this line if necessary for specific options

    - name: Test with pytest for Calculator Application
      run: |
        echo "Running tests for the Calculator application..."
        pytest --num_records=10  # Adjust this line if necessary for specific options
